import React from "react";
import { css } from "@emotion/react";
import { Package } from "../util/package";
import SiteData from "../util/site-data";
const ReactMarkdown = require("react-markdown");
const gfm = require("remark-gfm");

export default function Homepage({
  name,
  version,
  repositoryUrl,
  logoIcon,
  readme
}: SiteData): React.ReactElement {
  const generalStyles = css({
    a: {
      color: "#1f7199",
      textDecorationColor: "#1f719940"
    },
    ":target": {
      color: "#005680"
    },
    "h1 h2 h3 h4 h5 h6": {
      a: {
        color: "inherit",
        textDecoration: "none",
        position: "relative",
        ":hover": {
          "::before": {
            content: '"\\1F517"',
            display: "inline-block",
            width: "1.5em",
            position: "absolute",
            left: "-1.5em"
          }
        }
      }
    },
    pre: {
      border: "1px solid #e0e0e8"
    }
  });

  const repoUrl = repositoryUrl
    ?.replace(/^git\+/, "")
    ?.replace(/^git@github.com:/, "https://github.com/");

  return (
    <div
      css={[
        {
          width: 600,
          margin: "auto",
          textAlign: "center"
        },
        generalStyles
      ]}
    >
      <h1>{name}</h1>
      <h2>version {version}</h2>

      <nav
        css={{
          ul: {
            listStyleType: "none",
            padding: 0,
            li: {
              padding: "0 1em",
              borderLeft: "1px solid gray",
              display: "inline",
              ":first-child": {
                borderLeft: "none"
              }
            }
          }
        }}
      >
        <ul>
          <li>
            <a
              href="#for-humans"
              title="Jump to the Reports for Humans section of this page"
            >
              reports for humans
            </a>
          </li>
          <li>
            <a
              href="#for-machines"
              title="Jump to the Reports for Machines section of this page"
            >
              reports for machines
            </a>
          </li>
          <li>
            <a href="#readme" title="Jump to the README section of this page">
              readme
            </a>
          </li>
          <li>
            <a href="api/index.html" title="View API Docs">
              api
            </a>
          </li>
          <li>
            <a href="src.html" title="View source code for this version">
              src
            </a>
          </li>
          {repoUrl && (
            <li>
              <a href={repoUrl} title="View project repo">
                repo
              </a>
            </li>
          )}
        </ul>
      </nav>

      <section
        id="top-matter"
        css={{
          ul: {
            listStyleType: "none",
            padding: 0
          }
        }}
      >
        {logoIcon && (
          <img
            id="logo"
            src={logoIcon.href}
            width={logoIcon.width}
            height={logoIcon.height}
            alt={`Project logo for ${name}`}
          />
        )}

        <h2 id="for-humans">
          <a href="#for-humans" title="link to this section">
            Reports for Humans
          </a>
        </h2>
        <ul>
          <li>
            <a
              href="reports/unit-tests/index.html"
              title="Unit test report generated by jest-stare"
            >
              Unit tests (stare)
            </a>
          </li>
          <li>
            <a
              href="reports/coverage/lcov-report/index.html"
              title="Code coverage report"
            >
              Code Coverage
            </a>
          </li>
        </ul>

        <h2 id="for-machines">
          <a href="#for-machines" title="link to this section">
            Reports for Machines
          </a>
        </h2>
        <ul>
          <li>
            <a
              href="reports/xunit.xml"
              title="xunit-format XML results for unit tests"
            >
              Xunit Results (XML)
            </a>
          </li>
          <li>
            <a
              href="reports/coverage/cobertura-coverage.xml"
              title="Cobertura format code coverage results"
            >
              Cobertura Code Coverage (XML)
            </a>
          </li>
          <li>
            <a
              href="reports/coverage/clover.xml"
              title="Clover format code coverage results"
            >
              Clover Code Coverage (XML)
            </a>
          </li>
          <li>
            <a
              href="reports/coverage/lcov.info"
              title="LCOV format code coverage results"
            >
              LCOV Code Coverage
            </a>
          </li>
          <li>
            <a
              href="reports/coverage/coverage-final.json"
              title="JSON format code coverage results"
            >
              JSON Code Coverage
            </a>
          </li>
        </ul>
      </section>

      <h2 id="readme">
        <a href="#readme" title="link to this section">
          README
        </a>
      </h2>
      <section
        id="readme-section"
        css={{
          textAlign: "left",
          "h1 h2 h3 h4 h5 h6": {
            textAlign: "center"
          }
        }}
      >
        <ReactMarkdown plugins={[gfm]} children={readme} />
      </section>
    </div>
  );
}
